### ISSUE TITLE
Default Export Support

### ISSUE THREAD

**Issue by Skillz4Killz** [gc/confusables#3]
![image](https://user-images.githubusercontent.com/23035000/67967143-6f95ab00-fbdb-11e9-8055-6faedf6161d3.png)

**Comment by gc** [comment]
Does `import * as confusables from 'confusables';` work for you?

**Comment by Skillz4Killz** [comment]
It does work but having support for default exports is much cleaner.

**Comment by gc** [comment]
May I ask why you dont simply just `import { remove } `? Your welcome to create a PR so `import * as` isn't required. `npm run dev` to run it in dev, `node test/test` to run the tests.

**Comment by Skillz4Killz** [comment]
Because { remove } hides the context. If you try and use remove() 200 lines below its not entirely clear where this remove is from or what it does. What is it removing? how is it removing? why is it removing? You have to scroll to the top to find out then go down again to continue. 
But using something like `confusables.remove()` is much more clear and you instantly know everything about what you're trying to do in that line. Imagine you have another file as well that does remove like if you are trying to remove XP. Trying to import both with { remove} doesn't work. 
+1 maintainability and readability

Just to be clear the `* as confusables` already works great. Just support for default exports is cleaner

**Comment by gc** [comment]
you can do `import { remove: removeConfusables }` so it imports `remove` but renames it to `removeConfusables`

**Comment by Skillz4Killz** [comment]
Its cleaner to do `* as confusables` then that but `import confusables from 'confusables'` would be the best.
